version: '3.8'

services:
  bot:
    build: .
    container_name: 8800-telegram-bot
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
