version: '3.8'

services:
  proxy:
    build: .
    container_name: 8800-proxy-server
    restart: always
    ports:
      - "1080:1080"
    environment:
      # API валидация (включи когда настроишь API на сервере с ботом)
      - USE_API_VALIDATION=false
      # URL API сервера с ботом
      - API_URL=http://194.87.102.170:5000/verify
      # Секретный токен
      - API_TOKEN=BooHagZ2Hy2-Hi9prVvMuC99Yvqa6yvPNFzRxtjNRI8
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
