services:
  mtproto:
    build: .
    image: mtproto-proxy:latest
    container_name: mtproto-proxy
    restart: always
    ports:
      - "8800:8800"
    environment:
      - PROXY_DOMAIN=8800.life
      - PROXY_PORT=8800
      - MTPROTO_SECRET=dd2ae5891b2b9b9b811b212050843193aa
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
