services:
  mtproxy:
    image: telegrammessenger/proxy:latest
    container_name: 8800-mtproxy
    restart: always
    network_mode: host
    environment:
      - SECRET=dd2ae5891b2b9b9b811b212050843193aa
    command: >
      sh -c "curl -s https://core.telegram.org/getProxySecret -o /opt/mtproto-proxy/proxy-secret &&
             curl -s https://core.telegram.org/getProxyConfig -o /opt/mtproto-proxy/proxy-multi.conf &&
             /opt/mtproto-proxy/mtproto-proxy -u nobody -p 8800 -H 8443 -S dd2ae5891b2b9b9b811b212050843193aa --aes-pwd /opt/mtproto-proxy/proxy-secret /opt/mtproto-proxy/proxy-multi.conf -M 1 -v"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
