server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /sub {
        default_type text/plain;
        add_header Content-Disposition 'attachment; filename="8800connections"';
        add_header Profile-Title '8800 connections';
        add_header Subscription-Userinfo 'upload=0; download=0; total=0; expire=0';
        add_header Profile-Update-Interval '12';
        add_header Support-Url 'https://t.me/connections8800';
    }
}
